### ISSUE TITLE
Function to export grid/cell means

### ISSUE THREAD

**Issue by fredjaya** [roblanf/eucbase#2]
Split the current commit of alaGridMean.R to calculate species means (i.e alaPopMean) and species means per grid (i.e. alaGridMean2). 

- [x] Assign unique cellIDs
- [x] Assign lat/longs per cellID

**Comment by roblanf** [comment]
Just a note on this: don't rename the function x to x2 (not sure if you were going to do this...). 

But in this case, just keep an `alaGridMean` function named as it is. That's a good informative name. 

And what about `alaSpeciesMean` for the other one - then it's perhaps clearer that you will base the grouping on a species column in the input.

**Comment by fredjaya** [comment]
`alaGridMean.R` and `alaSpeciesMean.R` amended/completed and committed.
